name: gdl_watermark
description: Flutter_GDL Package to display the logo on every meetup sample
version: 0.0.1
author: The Flutter Guadalajara meetup team
homepage: https://github.com/Flutter-GDL/gdl_watermark

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^ 0.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:

  assets:
    - assets/corazon.png
    - assets/mexico.png

