name: gdl_watermark
description: Flutter_GDL Package to display the logo on every meetup sample
version: 0.1.0
author: The Flutter Guadalajara meetup team
homepage: https://github.com/Flutter-GDL/gdl_watermark

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^ 0.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  glob:


# The following section is specific to Flutter.
flutter:

  assets:
    - assets/corazon.png
    - assets/mexico.png

# 0.1.0
#     Added Flex, Container Embedding and Ability to disable 20 px bottom padding (sizeBox)

# 0.0.1 (initial launch)
